<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2010-07-26 17:18

$extensionPath = t3lib_extMgm::extPath('macina_banners');
return array(
	'tx_macinabanners_tt_content_tx_macinabanners_placement' => $extensionPath . 'class.tx_macinabanners_tt_content_tx_macinabanners_placement.php'
);
?>
