<?php
/**
 * Language labels for database tables/fields belonging to extension "macina_banners"
 * 
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'tt_content.tx_macinabanners_placement.I.0' => 'top',
		'tt_content.tx_macinabanners_placement.I.1' => 'right',
		'tt_content.tx_macinabanners_placement.I.2' => 'bottom',
		'tt_content.tx_macinabanners_placement.I.3' => 'left',
		'tt_content.tx_macinabanners_placement' => 'Placement',
		'tt_content.tx_macinabanners_mode.I.0' => 'show all attached banner',
		'tt_content.tx_macinabanners_mode.I.1' => 'show random from attached banners',
		//medialights: add "all banners randomized" mode
		'tt_content.tx_macinabanners_mode.I.2' => 'show all banners randomized',
		'tt_content.tx_macinabanners_mode' => 'Mode',
		'tx_macinabanners_banners' => 'Banner',
		'tx_macinabanners_banners.customer' => 'Customer',
		'tx_macinabanners_banners.bannertype.I.0' => 'image',
		'tx_macinabanners_banners.bannertype.I.1' => 'flash (.swf)',
		'tx_macinabanners_banners.bannertype.I.2' => 'html',
		'tx_macinabanners_banners.bannertype' => 'Bannertype',
		'tx_macinabanners_banners.image' => 'Bannerimage',
		'tx_macinabanners_banners.maxw' => 'maximum width',
		'tx_macinabanners_banners.alttext' => 'Image Text',
		'tx_macinabanners_banners.url' => 'Link',
		'tx_macinabanners_banners.swf' => 'flashbanner',
		'tx_macinabanners_banners.flash_width' => 'width of flashmovie',
		'tx_macinabanners_banners.flash_height' => 'height of flashmovie',
		'tx_macinabanners_banners.placement.I.0' => 'top',
		'tx_macinabanners_banners.placement.I.1' => 'right',
		'tx_macinabanners_banners.placement.I.2' => 'bottom',
		'tx_macinabanners_banners.placement.I.3' => 'left',
		'tx_macinabanners_banners.placement' => 'Placement',
		'tx_macinabanners_banners.border_top' => 'top Border',
		'tx_macinabanners_banners.border_right' => 'right Border',
		'tx_macinabanners_banners.border_bottom' => 'bottom Border',
		'tx_macinabanners_banners.border_left' => 'left Border',
		'tx_macinabanners_banners.pages' => 'Show Banner on this Pages ONLY',
		'tx_macinabanners_banners.recursiv' => 'including Subpages',
		'tx_macinabanners_banners.excludepages' => 'DONT show Banner on THIS Pages',
		'tx_macinabanners_banners.impressions' => 'Impressions',
		'tx_macinabanners_banners.clicks' => 'Clickcount',
		'tx_macinabanners_banners.parameters' => 'Parameters',
		'tt_content.list_type_pi1' => 'Bannermodule',
		'tx_macinabanners_banners.sys_language_uid' => 'Banner language',
		'tx_macinabanners_banners.sys_language_independent' => 'Language independent (above seleceted language is ignored!)',
		'tx_macinabanners_banners.general' => 'General',
		'tx_macinabanners_banners.bannerimage' => 'BannerImage',
		'tx_macinabanners_banners.flashfilm' => 'Flashfile',
		'tx_macinabanners_banners.html' => 'HTML',
		'tx_macinabanners_banners.view' => 'View',
		'tx_macinabanners_banners.visibility' => 'Visibility',
		'tx_macinabanners_banners.statistics' => 'Statistics',
		
		'tx_macinabanners_categories' => 'Banner Category',    
		'tx_macinabanners_categories.description' => 'Description',
		'tx_macinabanners_categories.icon' => 'Icon',
	),
	'dk' => Array (
	),
	'de' => Array (
		'tt_content.tx_macinabanners_placement.I.0' => 'oben',
		'tt_content.tx_macinabanners_placement.I.1' => 'rechts',
		'tt_content.tx_macinabanners_placement.I.2' => 'unten',
		'tt_content.tx_macinabanners_placement.I.3' => 'links',
		'tt_content.tx_macinabanners_placement' => 'Positionierug',
		'tt_content.tx_macinabanners_mode.I.0' => 'alle dieser Seite angef�gten Banner zeigen',
		'tt_content.tx_macinabanners_mode.I.1' => 'zuf�llig einen der angef�gten Banner zeigen',
		'tt_content.tx_macinabanners_mode.I.2' => 'alle Banner in zuf�lliger Reihenfolge zeigen',
		'tt_content.tx_macinabanners_mode' => 'Anzeigemodus',
		'tx_macinabanners_banners' => 'Banner',
		'tx_macinabanners_banners.customer' => 'Beschreibung',
		'tx_macinabanners_banners.bannertype.I.0' => 'Bild',
		'tx_macinabanners_banners.bannertype.I.1' => 'Flash (.swf)',
		'tx_macinabanners_banners.bannertype.I.2' => 'Html',
		'tx_macinabanners_banners.bannertype' => 'Bannertyp',
		'tx_macinabanners_banners.image' => 'Bannerbilddatei',
		'tx_macinabanners_banners.maxw' => 'maximale Breite',
		'tx_macinabanners_banners.alttext' => 'Bildtext',
		'tx_macinabanners_banners.url' => 'Link',
		'tx_macinabanners_banners.swf' => 'Flashbanner',
		'tx_macinabanners_banners.flash_width' => 'Breite des Flashfilms',
		'tx_macinabanners_banners.flash_height' => 'H�he des Flashfilms',
		'tx_macinabanners_banners.placement.I.0' => 'oben',
		'tx_macinabanners_banners.placement.I.1' => 'rechts',
		'tx_macinabanners_banners.placement.I.2' => 'unten',
		'tx_macinabanners_banners.placement.I.3' => 'links',
		'tx_macinabanners_banners.placement' => 'Positionierug',
		'tx_macinabanners_banners.border_top' => 'oberer Rand',
		'tx_macinabanners_banners.border_right' => 'rechter Rand',
		'tx_macinabanners_banners.border_bottom' => 'unterer Rand',
		'tx_macinabanners_banners.border_left' => 'linker Rand',
		'tx_macinabanners_banners.pages' => 'zeige Banner NUR auf diesen Seiten',
		'tx_macinabanners_banners.recursiv' => 'inclusive Unterseiten',
		'tx_macinabanners_banners.excludepages' => 'zeige Banner NICHT auf diesen Seiten',
		'tx_macinabanners_banners.impressions' => 'Darstellungen',
		'tx_macinabanners_banners.clicks' => 'Anzahl von Clicks',
		'tx_macinabanners_banners_parameters' => 'Parameter',    
		'tt_content.list_type_pi1' => 'Bannermodul',
		'tx_macinabanners_banners.sys_language_uid' => 'Sprache des Banners',
		'tx_macinabanners_banners.sys_language_independent' => 'Sprachunabh�ngig (obige Auswahl wird ignoriert!)',
		'tx_macinabanners_banners.general' => 'Grundeinstellungen',
		'tx_macinabanners_banners.bannerimage' => 'Bannergrafik',
		'tx_macinabanners_banners.flashfilm' => 'Flashfilm',
		'tx_macinabanners_banners.html' => 'HTML',
		'tx_macinabanners_banners.view' => 'Anzeige',
		'tx_macinabanners_banners.visibility' => 'Sichtbarkeit',
		'tx_macinabanners_banners.statistics' => 'Statistik',
		
		'tx_macinabanners_categories' => 'Banner Kategorie',    
		'tx_macinabanners_categories.description' => 'Beschreibung',  		
		'tx_macinabanners_categories.icon' => 'Icon',
	),
	'no' => Array (
		'tt_content.tx_macinabanners_placement.I.0' => 'topp',
		'tt_content.tx_macinabanners_placement.I.1' => 'h�yre',
		'tt_content.tx_macinabanners_placement.I.2' => 'bunn',
		'tt_content.tx_macinabanners_placement.I.3' => 'venstre',
		'tt_content.tx_macinabanners_placement' => 'Plassering',
		'tt_content.tx_macinabanners_mode.I.0' => 'Vis alle tilknyttede bannere',
		'tt_content.tx_macinabanners_mode.I.1' => 'Vis tilfeldig banner blant de tilknyttede',
		'tt_content.tx_macinabanners_mode' => 'Modus',
		'tx_macinabanners_banners' => 'Banner',
		'tx_macinabanners_banners.customer' => 'Kunde',
		'tx_macinabanners_banners.bannertype.I.0' => 'grafikk/bilde',
		'tx_macinabanners_banners.bannertype.I.1' => 'Flash-fil (.swf)',
		'tx_macinabanners_banners.bannertype.I.2' => 'html',
		'tx_macinabanners_banners.bannertype' => 'Type banner',
		'tx_macinabanners_banners.image' => 'Bilde',
		'tx_macinabanners_banners.maxw' => 'Max. bredde',
		'tx_macinabanners_banners.alttext' => 'Bildetekst',
		'tx_macinabanners_banners.url' => 'Lenke',
		'tx_macinabanners_banners.swf' => 'Flash-banner',
		'tx_macinabanners_banners.flash_width' => 'Bredde p� Flash-filmen',
		'tx_macinabanners_banners.flash_height' => 'H�yde p� Flash-filmen',
		'tx_macinabanners_banners.placement.I.0' => 'top',
		'tx_macinabanners_banners.placement.I.1' => 'h�yre',
		'tx_macinabanners_banners.placement.I.2' => 'bunn',
		'tx_macinabanners_banners.placement.I.3' => 'venstre',
		'tx_macinabanners_banners.placement' => 'Plassering',
		'tx_macinabanners_banners.border_top' => 'Luft over',
		'tx_macinabanners_banners.border_right' => 'Luft til h�yre',
		'tx_macinabanners_banners.border_bottom' => 'Luft under',
		'tx_macinabanners_banners.border_left' => 'Luft til venstre',
		'tx_macinabanners_banners.pages' => 'Vis banneret p� disse sidene',
		'tx_macinabanners_banners.impressions' => 'Antall visninger',
		'tx_macinabanners_banners.clicks' => 'Antall klikk',
		'tt_content.list_type_pi1' => 'Reklamemodul',
	),
	'it' => Array (
	),
	'fr' => Array (
	),
	'es' => Array (
		'tt_content.tx_macinabanners_placement.I.0' => 'Superior',
		'tt_content.tx_macinabanners_placement.I.1' => 'Derecha',
		'tt_content.tx_macinabanners_placement.I.2' => 'Inferior',
		'tt_content.tx_macinabanners_placement.I.3' => 'Izquierda',
		'tt_content.tx_macinabanners_placement' => 'Posici�n',
		'tt_content.tx_macinabanners_mode.I.0' => 'Mostrar todos los banners',
		'tt_content.tx_macinabanners_mode.I.1' => 'Mostrar un banner de manera aleatoria',
		'tt_content.tx_macinabanners_mode' => 'Modo',
		'tx_macinabanners_banners' => 'Banner',
		'tx_macinabanners_banners.customer' => 'Cliente',
		'tx_macinabanners_banners.bannertype.I.0' => 'Imagen (.jpg,.gif,.png,etc)',
		'tx_macinabanners_banners.bannertype.I.1' => 'Macromedia Flash (.swf)',
		'tx_macinabanners_banners.bannertype.I.2' => 'html',
		'tx_macinabanners_banners.bannertype' => 'Tipo de banner',
		'tx_macinabanners_banners.image' => 'Imagen del banner',
		'tx_macinabanners_banners.maxw' => 'Ancho m�ximo',
		'tx_macinabanners_banners.alttext' => 'Texto asociado',
		'tx_macinabanners_banners.url' => 'Enlace',
		'tx_macinabanners_banners.swf' => 'Pel�cula Flash',
		'tx_macinabanners_banners.flash_width' => 'Ancho',
		'tx_macinabanners_banners.flash_height' => 'Alto',
		'tx_macinabanners_banners.placement.I.0' => 'Superior',
		'tx_macinabanners_banners.placement.I.1' => 'Derecha',
		'tx_macinabanners_banners.placement.I.2' => 'Inferior',
		'tx_macinabanners_banners.placement.I.3' => 'Izquierda',
		'tx_macinabanners_banners.placement' => 'Posici�n',
		'tx_macinabanners_banners.border_top' => 'Borde superior',
		'tx_macinabanners_banners.border_right' => 'Borde derecho',
		'tx_macinabanners_banners.border_bottom' => 'Borde inferior',
		'tx_macinabanners_banners.border_left' => 'Borde izquierdo',
		'tx_macinabanners_banners.pages' => 'Mostrar banner SOLO en las siguientes p�ginas',
		'tx_macinabanners_banners.recursiv' => 'Incluir subp�ginas',
		'tx_macinabanners_banners.excludepages' => 'NO mostrar este banner en las siguientes paginas',
		'tx_macinabanners_banners.impressions' => 'Impresiones',
		'tx_macinabanners_banners.clicks' => 'N�mero de Clics',
		'tt_content.list_type_pi1' => 'M�dulo de banners',
		'tx_macinabanners_banners.sys_language_uid' => 'Idioma del banner',
		'tx_macinabanners_banners.sys_language_independent' => 'Independiente del idioma (ignorar los idiomas)',
		'tx_macinabanners_banners.general' => 'General',
		'tx_macinabanners_banners.bannerimage' => 'Im�genes del banner',
		'tx_macinabanners_banners.flashfilm' => 'Pel�culas Flash',
		'tx_macinabanners_banners.html' => 'HTML',
		'tx_macinabanners_banners.view' => 'Ver',
		'tx_macinabanners_banners.visibility' => 'Visibilidad',
		'tx_macinabanners_banners.statistics' => 'Estadisticas',
	),
	'nl' => Array (
	),
	'cz' => Array (
	),
	'pl' => Array (
	),
	'si' => Array (
	),
	'fi' => Array (
		'tt_content.tx_macinabanners_placement.I.0' => 'yl�s',
		'tt_content.tx_macinabanners_placement.I.1' => 'oikealle',
		'tt_content.tx_macinabanners_placement.I.2' => 'alas',
		'tt_content.tx_macinabanners_placement.I.3' => 'vasemmalle',
		'tt_content.tx_macinabanners_placement' => 'Sijainti',
		'tt_content.tx_macinabanners_mode.I.0' => 'n�yt� kaikki liitetyt mainospalkit',
		'tt_content.tx_macinabanners_mode.I.1' => 'n�yt� satunnaisesti liitetyist� mainospalkeista',
		'tt_content.tx_macinabanners_mode' => 'Moodi',
		'tx_macinabanners_banners' => 'Mainospalkki',
		'tx_macinabanners_banners.customer' => 'Asiakas',
		'tx_macinabanners_banners.bannertype.I.0' => 'kuva',
		'tx_macinabanners_banners.bannertype.I.1' => 'flash (.swf)',
		'tx_macinabanners_banners.bannertype.I.2' => 'html',
		'tx_macinabanners_banners.bannertype' => 'Mainospalkin tyyppi',
		'tx_macinabanners_banners.image' => 'Mainospalkin kuva',
		'tx_macinabanners_banners.maxw' => 'maksimi leveys',
		'tx_macinabanners_banners.alttext' => 'Kuvan teksti',
		'tx_macinabanners_banners.url' => 'Linkki',
		'tx_macinabanners_banners.swf' => 'flash mainospalkki',
		'tx_macinabanners_banners.flash_width' => 'flash elokuvan leveys',
		'tx_macinabanners_banners.flash_height' => 'flash elokuvan koskeus',
		'tx_macinabanners_banners.placement.I.0' => 'yl�s',
		'tx_macinabanners_banners.placement.I.1' => 'oikealle',
		'tx_macinabanners_banners.placement.I.2' => 'alas',
		'tx_macinabanners_banners.placement.I.3' => 'vasemmalle',
		'tx_macinabanners_banners.placement' => 'Sijainto',
		'tx_macinabanners_banners.border_top' => 'yl� raja',
		'tx_macinabanners_banners.border_right' => 'oikea raja',
		'tx_macinabanners_banners.border_bottom' => 'ala raja',
		'tx_macinabanners_banners.border_left' => 'vasen raja',
		'tx_macinabanners_banners.pages' => 'N�yt� mainospalkki n�ill� sivuilla',
		'tx_macinabanners_banners.recursiv' => 'mukaan lukien alasivut',
		'tx_macinabanners_banners.excludepages' => '�L� n�yt� mainospallkkia T�LL� sivulla',
		'tx_macinabanners_banners.impressions' => 'Vaikutelmat',
		'tx_macinabanners_banners.clicks' => 'Valintalaskuri',
		'tt_content.list_type_pi1' => 'Mainospalkki aliohjelma',
		'tx_macinabanners_banners.sys_language_uid' => 'Mainospalkin kieli',
		'tx_macinabanners_banners.sys_language_independent' => 'Kielest� riippumaton (yll� valittu kieli ohitetaan!)',
		'tx_macinabanners_banners.general' => 'Yleist�',
		'tx_macinabanners_banners.bannerimage' => 'Mainospalkin kuva',
		'tx_macinabanners_banners.flashfilm' => 'Flashtiedosto',
		'tx_macinabanners_banners.html' => 'HTML',
		'tx_macinabanners_banners.view' => 'N�yt�',
		'tx_macinabanners_banners.visibility' => 'N�kyvyys',
		'tx_macinabanners_banners.statistics' => 'Tilastot',
	),
	'tr' => Array (
	),
	'se' => Array (
	),
	'pt' => Array (
	),
	'ru' => Array (
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
		'tt_content.tx_macinabanners_placement.I.0' => 'vrh',
		'tt_content.tx_macinabanners_placement.I.1' => 'desno',
		'tt_content.tx_macinabanners_placement.I.2' => 'dno',
		'tt_content.tx_macinabanners_placement.I.3' => 'lijevo',
		'tt_content.tx_macinabanners_placement' => 'Mjesto',
		'tt_content.tx_macinabanners_mode.I.0' => 'prika�i sve prilo�ene bannere',
		'tt_content.tx_macinabanners_mode.I.1' => 'prika�i nasumi�no prilo�ene bannere',
		'tt_content.tx_macinabanners_mode' => 'Mod',
		'tx_macinabanners_banners' => 'Banner',
		'tx_macinabanners_banners.customer' => 'Klijent',
		'tx_macinabanners_banners.bannertype.I.0' => 'slika',
		'tx_macinabanners_banners.bannertype.I.1' => 'flash (.swf)',
		'tx_macinabanners_banners.bannertype.I.2' => 'html',
		'tx_macinabanners_banners.bannertype' => 'Tip bannera',
		'tx_macinabanners_banners.image' => 'Slika za banner',
		'tx_macinabanners_banners.maxw' => 'maksimalna �irina',
		'tx_macinabanners_banners.alttext' => 'Tekst za sliku',
		'tx_macinabanners_banners.url' => 'Link',
		'tx_macinabanners_banners.swf' => 'flashbanner',
		'tx_macinabanners_banners.flash_width' => '�irina flasha',
		'tx_macinabanners_banners.flash_height' => 'visina flasha',
		'tx_macinabanners_banners.placement.I.0' => 'vrh',
		'tx_macinabanners_banners.placement.I.1' => 'desno',
		'tx_macinabanners_banners.placement.I.2' => 'dno',
		'tx_macinabanners_banners.placement.I.3' => 'lijevo',
		'tx_macinabanners_banners.placement' => 'Mjesto',
		'tx_macinabanners_banners.border_top' => 'okvir na vrhu',
		'tx_macinabanners_banners.border_right' => 'okvir desno',
		'tx_macinabanners_banners.border_bottom' => 'odvir dno',
		'tx_macinabanners_banners.border_left' => 'okvir lijevo',
		'tx_macinabanners_banners.pages' => 'Prika�i banner na stranicama:',
		'tx_macinabanners_banners.impressions' => 'Prikazivanja',
		'tx_macinabanners_banners.clicks' => 'Broj likovi',
		'tt_content.list_type_pi1' => 'Banner modul',
	),
	'hu' => Array (
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
	'eo' => Array (
	),
	'my' => Array (
	),
	'hi' => Array (
	),
);
?>
